apiVersion: v1
kind: ConfigMap
metadata:
  name: commonwell-config
  labels:
    app: commonwell-query
data:
  NODE_ENV: "production"
  CW_ORG_OID: "2.16.840.1.113883.3.5958.1000.300"
  CW_ORG_NAME: "CVS Health"
  CLEAR_OID: "2.16.840.1.113883.3.5958.1000.300.1"
  CLIENT_CERT_PATH: "/app/certs/client-cert.pem"
  CLIENT_KEY_PATH: "/app/certs/client-key.pem"
