apiVersion: v1
kind: Service
metadata:
  name: commonwell-query-service
  labels:
    app: commonwell-query
spec:
  type: LoadBalancer
  selector:
    app: commonwell-query
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
